# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/vogel/BORG/MABOX_FLEX/Documents/cli-visualizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/vogel/BORG/MABOX_FLEX/Documents/cli-visualizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/vogel/BORG/MABOX_FLEX/Documents/cli-visualizer/CMakeFiles /run/media/vogel/BORG/MABOX_FLEX/Documents/cli-visualizer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/vogel/BORG/MABOX_FLEX/Documents/cli-visualizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vis

# Build rule for target.
vis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vis
.PHONY : vis

# fast build rule for target.
vis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/build
.PHONY : vis/fast

src/Domain/ColorDefinition.o: src/Domain/ColorDefinition.cpp.o
.PHONY : src/Domain/ColorDefinition.o

# target to build an object file
src/Domain/ColorDefinition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/ColorDefinition.cpp.o
.PHONY : src/Domain/ColorDefinition.cpp.o

src/Domain/ColorDefinition.i: src/Domain/ColorDefinition.cpp.i
.PHONY : src/Domain/ColorDefinition.i

# target to preprocess a source file
src/Domain/ColorDefinition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/ColorDefinition.cpp.i
.PHONY : src/Domain/ColorDefinition.cpp.i

src/Domain/ColorDefinition.s: src/Domain/ColorDefinition.cpp.s
.PHONY : src/Domain/ColorDefinition.s

# target to generate assembly for a file
src/Domain/ColorDefinition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/ColorDefinition.cpp.s
.PHONY : src/Domain/ColorDefinition.cpp.s

src/Domain/Settings.o: src/Domain/Settings.cpp.o
.PHONY : src/Domain/Settings.o

# target to build an object file
src/Domain/Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/Settings.cpp.o
.PHONY : src/Domain/Settings.cpp.o

src/Domain/Settings.i: src/Domain/Settings.cpp.i
.PHONY : src/Domain/Settings.i

# target to preprocess a source file
src/Domain/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/Settings.cpp.i
.PHONY : src/Domain/Settings.cpp.i

src/Domain/Settings.s: src/Domain/Settings.cpp.s
.PHONY : src/Domain/Settings.s

# target to generate assembly for a file
src/Domain/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/Settings.cpp.s
.PHONY : src/Domain/Settings.cpp.s

src/Domain/VisException.o: src/Domain/VisException.cpp.o
.PHONY : src/Domain/VisException.o

# target to build an object file
src/Domain/VisException.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/VisException.cpp.o
.PHONY : src/Domain/VisException.cpp.o

src/Domain/VisException.i: src/Domain/VisException.cpp.i
.PHONY : src/Domain/VisException.i

# target to preprocess a source file
src/Domain/VisException.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/VisException.cpp.i
.PHONY : src/Domain/VisException.cpp.i

src/Domain/VisException.s: src/Domain/VisException.cpp.s
.PHONY : src/Domain/VisException.s

# target to generate assembly for a file
src/Domain/VisException.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Domain/VisException.cpp.s
.PHONY : src/Domain/VisException.cpp.s

src/Source/AudioSource.o: src/Source/AudioSource.cpp.o
.PHONY : src/Source/AudioSource.o

# target to build an object file
src/Source/AudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/AudioSource.cpp.o
.PHONY : src/Source/AudioSource.cpp.o

src/Source/AudioSource.i: src/Source/AudioSource.cpp.i
.PHONY : src/Source/AudioSource.i

# target to preprocess a source file
src/Source/AudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/AudioSource.cpp.i
.PHONY : src/Source/AudioSource.cpp.i

src/Source/AudioSource.s: src/Source/AudioSource.cpp.s
.PHONY : src/Source/AudioSource.s

# target to generate assembly for a file
src/Source/AudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/AudioSource.cpp.s
.PHONY : src/Source/AudioSource.cpp.s

src/Source/MpdAudioSource.o: src/Source/MpdAudioSource.cpp.o
.PHONY : src/Source/MpdAudioSource.o

# target to build an object file
src/Source/MpdAudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/MpdAudioSource.cpp.o
.PHONY : src/Source/MpdAudioSource.cpp.o

src/Source/MpdAudioSource.i: src/Source/MpdAudioSource.cpp.i
.PHONY : src/Source/MpdAudioSource.i

# target to preprocess a source file
src/Source/MpdAudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/MpdAudioSource.cpp.i
.PHONY : src/Source/MpdAudioSource.cpp.i

src/Source/MpdAudioSource.s: src/Source/MpdAudioSource.cpp.s
.PHONY : src/Source/MpdAudioSource.s

# target to generate assembly for a file
src/Source/MpdAudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/MpdAudioSource.cpp.s
.PHONY : src/Source/MpdAudioSource.cpp.s

src/Source/PortAudioSource.o: src/Source/PortAudioSource.cpp.o
.PHONY : src/Source/PortAudioSource.o

# target to build an object file
src/Source/PortAudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PortAudioSource.cpp.o
.PHONY : src/Source/PortAudioSource.cpp.o

src/Source/PortAudioSource.i: src/Source/PortAudioSource.cpp.i
.PHONY : src/Source/PortAudioSource.i

# target to preprocess a source file
src/Source/PortAudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PortAudioSource.cpp.i
.PHONY : src/Source/PortAudioSource.cpp.i

src/Source/PortAudioSource.s: src/Source/PortAudioSource.cpp.s
.PHONY : src/Source/PortAudioSource.s

# target to generate assembly for a file
src/Source/PortAudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PortAudioSource.cpp.s
.PHONY : src/Source/PortAudioSource.cpp.s

src/Source/PulseAudioSource.o: src/Source/PulseAudioSource.cpp.o
.PHONY : src/Source/PulseAudioSource.o

# target to build an object file
src/Source/PulseAudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PulseAudioSource.cpp.o
.PHONY : src/Source/PulseAudioSource.cpp.o

src/Source/PulseAudioSource.i: src/Source/PulseAudioSource.cpp.i
.PHONY : src/Source/PulseAudioSource.i

# target to preprocess a source file
src/Source/PulseAudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PulseAudioSource.cpp.i
.PHONY : src/Source/PulseAudioSource.cpp.i

src/Source/PulseAudioSource.s: src/Source/PulseAudioSource.cpp.s
.PHONY : src/Source/PulseAudioSource.s

# target to generate assembly for a file
src/Source/PulseAudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/PulseAudioSource.cpp.s
.PHONY : src/Source/PulseAudioSource.cpp.s

src/Source/ShmemAudioSource.o: src/Source/ShmemAudioSource.cpp.o
.PHONY : src/Source/ShmemAudioSource.o

# target to build an object file
src/Source/ShmemAudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/ShmemAudioSource.cpp.o
.PHONY : src/Source/ShmemAudioSource.cpp.o

src/Source/ShmemAudioSource.i: src/Source/ShmemAudioSource.cpp.i
.PHONY : src/Source/ShmemAudioSource.i

# target to preprocess a source file
src/Source/ShmemAudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/ShmemAudioSource.cpp.i
.PHONY : src/Source/ShmemAudioSource.cpp.i

src/Source/ShmemAudioSource.s: src/Source/ShmemAudioSource.cpp.s
.PHONY : src/Source/ShmemAudioSource.s

# target to generate assembly for a file
src/Source/ShmemAudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Source/ShmemAudioSource.cpp.s
.PHONY : src/Source/ShmemAudioSource.cpp.s

src/Transformer/EllipseTransformer.o: src/Transformer/EllipseTransformer.cpp.o
.PHONY : src/Transformer/EllipseTransformer.o

# target to build an object file
src/Transformer/EllipseTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/EllipseTransformer.cpp.o
.PHONY : src/Transformer/EllipseTransformer.cpp.o

src/Transformer/EllipseTransformer.i: src/Transformer/EllipseTransformer.cpp.i
.PHONY : src/Transformer/EllipseTransformer.i

# target to preprocess a source file
src/Transformer/EllipseTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/EllipseTransformer.cpp.i
.PHONY : src/Transformer/EllipseTransformer.cpp.i

src/Transformer/EllipseTransformer.s: src/Transformer/EllipseTransformer.cpp.s
.PHONY : src/Transformer/EllipseTransformer.s

# target to generate assembly for a file
src/Transformer/EllipseTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/EllipseTransformer.cpp.s
.PHONY : src/Transformer/EllipseTransformer.cpp.s

src/Transformer/GenericTransformer.o: src/Transformer/GenericTransformer.cpp.o
.PHONY : src/Transformer/GenericTransformer.o

# target to build an object file
src/Transformer/GenericTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/GenericTransformer.cpp.o
.PHONY : src/Transformer/GenericTransformer.cpp.o

src/Transformer/GenericTransformer.i: src/Transformer/GenericTransformer.cpp.i
.PHONY : src/Transformer/GenericTransformer.i

# target to preprocess a source file
src/Transformer/GenericTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/GenericTransformer.cpp.i
.PHONY : src/Transformer/GenericTransformer.cpp.i

src/Transformer/GenericTransformer.s: src/Transformer/GenericTransformer.cpp.s
.PHONY : src/Transformer/GenericTransformer.s

# target to generate assembly for a file
src/Transformer/GenericTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/GenericTransformer.cpp.s
.PHONY : src/Transformer/GenericTransformer.cpp.s

src/Transformer/LorenzTransformer.o: src/Transformer/LorenzTransformer.cpp.o
.PHONY : src/Transformer/LorenzTransformer.o

# target to build an object file
src/Transformer/LorenzTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/LorenzTransformer.cpp.o
.PHONY : src/Transformer/LorenzTransformer.cpp.o

src/Transformer/LorenzTransformer.i: src/Transformer/LorenzTransformer.cpp.i
.PHONY : src/Transformer/LorenzTransformer.i

# target to preprocess a source file
src/Transformer/LorenzTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/LorenzTransformer.cpp.i
.PHONY : src/Transformer/LorenzTransformer.cpp.i

src/Transformer/LorenzTransformer.s: src/Transformer/LorenzTransformer.cpp.s
.PHONY : src/Transformer/LorenzTransformer.s

# target to generate assembly for a file
src/Transformer/LorenzTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/LorenzTransformer.cpp.s
.PHONY : src/Transformer/LorenzTransformer.cpp.s

src/Transformer/SpectrumCircleTransformer.o: src/Transformer/SpectrumCircleTransformer.cpp.o
.PHONY : src/Transformer/SpectrumCircleTransformer.o

# target to build an object file
src/Transformer/SpectrumCircleTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumCircleTransformer.cpp.o
.PHONY : src/Transformer/SpectrumCircleTransformer.cpp.o

src/Transformer/SpectrumCircleTransformer.i: src/Transformer/SpectrumCircleTransformer.cpp.i
.PHONY : src/Transformer/SpectrumCircleTransformer.i

# target to preprocess a source file
src/Transformer/SpectrumCircleTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumCircleTransformer.cpp.i
.PHONY : src/Transformer/SpectrumCircleTransformer.cpp.i

src/Transformer/SpectrumCircleTransformer.s: src/Transformer/SpectrumCircleTransformer.cpp.s
.PHONY : src/Transformer/SpectrumCircleTransformer.s

# target to generate assembly for a file
src/Transformer/SpectrumCircleTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumCircleTransformer.cpp.s
.PHONY : src/Transformer/SpectrumCircleTransformer.cpp.s

src/Transformer/SpectrumTransformer.o: src/Transformer/SpectrumTransformer.cpp.o
.PHONY : src/Transformer/SpectrumTransformer.o

# target to build an object file
src/Transformer/SpectrumTransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumTransformer.cpp.o
.PHONY : src/Transformer/SpectrumTransformer.cpp.o

src/Transformer/SpectrumTransformer.i: src/Transformer/SpectrumTransformer.cpp.i
.PHONY : src/Transformer/SpectrumTransformer.i

# target to preprocess a source file
src/Transformer/SpectrumTransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumTransformer.cpp.i
.PHONY : src/Transformer/SpectrumTransformer.cpp.i

src/Transformer/SpectrumTransformer.s: src/Transformer/SpectrumTransformer.cpp.s
.PHONY : src/Transformer/SpectrumTransformer.s

# target to generate assembly for a file
src/Transformer/SpectrumTransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Transformer/SpectrumTransformer.cpp.s
.PHONY : src/Transformer/SpectrumTransformer.cpp.s

src/Utils/ConfigurationUtils.o: src/Utils/ConfigurationUtils.cpp.o
.PHONY : src/Utils/ConfigurationUtils.o

# target to build an object file
src/Utils/ConfigurationUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/ConfigurationUtils.cpp.o
.PHONY : src/Utils/ConfigurationUtils.cpp.o

src/Utils/ConfigurationUtils.i: src/Utils/ConfigurationUtils.cpp.i
.PHONY : src/Utils/ConfigurationUtils.i

# target to preprocess a source file
src/Utils/ConfigurationUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/ConfigurationUtils.cpp.i
.PHONY : src/Utils/ConfigurationUtils.cpp.i

src/Utils/ConfigurationUtils.s: src/Utils/ConfigurationUtils.cpp.s
.PHONY : src/Utils/ConfigurationUtils.s

# target to generate assembly for a file
src/Utils/ConfigurationUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/ConfigurationUtils.cpp.s
.PHONY : src/Utils/ConfigurationUtils.cpp.s

src/Utils/Logger.o: src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.o

# target to build an object file
src/Utils/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.cpp.o

src/Utils/Logger.i: src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.i

# target to preprocess a source file
src/Utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.cpp.i

src/Utils/Logger.s: src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.s

# target to generate assembly for a file
src/Utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.cpp.s

src/Utils/NcursesUtils.o: src/Utils/NcursesUtils.cpp.o
.PHONY : src/Utils/NcursesUtils.o

# target to build an object file
src/Utils/NcursesUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/NcursesUtils.cpp.o
.PHONY : src/Utils/NcursesUtils.cpp.o

src/Utils/NcursesUtils.i: src/Utils/NcursesUtils.cpp.i
.PHONY : src/Utils/NcursesUtils.i

# target to preprocess a source file
src/Utils/NcursesUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/NcursesUtils.cpp.i
.PHONY : src/Utils/NcursesUtils.cpp.i

src/Utils/NcursesUtils.s: src/Utils/NcursesUtils.cpp.s
.PHONY : src/Utils/NcursesUtils.s

# target to generate assembly for a file
src/Utils/NcursesUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/NcursesUtils.cpp.s
.PHONY : src/Utils/NcursesUtils.cpp.s

src/Utils/Utils.o: src/Utils/Utils.cpp.o
.PHONY : src/Utils/Utils.o

# target to build an object file
src/Utils/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Utils.cpp.o
.PHONY : src/Utils/Utils.cpp.o

src/Utils/Utils.i: src/Utils/Utils.cpp.i
.PHONY : src/Utils/Utils.i

# target to preprocess a source file
src/Utils/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Utils.cpp.i
.PHONY : src/Utils/Utils.cpp.i

src/Utils/Utils.s: src/Utils/Utils.cpp.s
.PHONY : src/Utils/Utils.s

# target to generate assembly for a file
src/Utils/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Utils/Utils.cpp.s
.PHONY : src/Utils/Utils.cpp.s

src/Visualizer.o: src/Visualizer.cpp.o
.PHONY : src/Visualizer.o

# target to build an object file
src/Visualizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Visualizer.cpp.o
.PHONY : src/Visualizer.cpp.o

src/Visualizer.i: src/Visualizer.cpp.i
.PHONY : src/Visualizer.i

# target to preprocess a source file
src/Visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Visualizer.cpp.i
.PHONY : src/Visualizer.cpp.i

src/Visualizer.s: src/Visualizer.cpp.s
.PHONY : src/Visualizer.s

# target to generate assembly for a file
src/Visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Visualizer.cpp.s
.PHONY : src/Visualizer.cpp.s

src/Writer/NcursesWriter.o: src/Writer/NcursesWriter.cpp.o
.PHONY : src/Writer/NcursesWriter.o

# target to build an object file
src/Writer/NcursesWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Writer/NcursesWriter.cpp.o
.PHONY : src/Writer/NcursesWriter.cpp.o

src/Writer/NcursesWriter.i: src/Writer/NcursesWriter.cpp.i
.PHONY : src/Writer/NcursesWriter.i

# target to preprocess a source file
src/Writer/NcursesWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Writer/NcursesWriter.cpp.i
.PHONY : src/Writer/NcursesWriter.cpp.i

src/Writer/NcursesWriter.s: src/Writer/NcursesWriter.cpp.s
.PHONY : src/Writer/NcursesWriter.s

# target to generate assembly for a file
src/Writer/NcursesWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/Writer/NcursesWriter.cpp.s
.PHONY : src/Writer/NcursesWriter.cpp.s

src/vis.o: src/vis.cpp.o
.PHONY : src/vis.o

# target to build an object file
src/vis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/vis.cpp.o
.PHONY : src/vis.cpp.o

src/vis.i: src/vis.cpp.i
.PHONY : src/vis.i

# target to preprocess a source file
src/vis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/vis.cpp.i
.PHONY : src/vis.cpp.i

src/vis.s: src/vis.cpp.s
.PHONY : src/vis.s

# target to generate assembly for a file
src/vis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vis.dir/build.make CMakeFiles/vis.dir/src/vis.cpp.s
.PHONY : src/vis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vis"
	@echo "... src/Domain/ColorDefinition.o"
	@echo "... src/Domain/ColorDefinition.i"
	@echo "... src/Domain/ColorDefinition.s"
	@echo "... src/Domain/Settings.o"
	@echo "... src/Domain/Settings.i"
	@echo "... src/Domain/Settings.s"
	@echo "... src/Domain/VisException.o"
	@echo "... src/Domain/VisException.i"
	@echo "... src/Domain/VisException.s"
	@echo "... src/Source/AudioSource.o"
	@echo "... src/Source/AudioSource.i"
	@echo "... src/Source/AudioSource.s"
	@echo "... src/Source/MpdAudioSource.o"
	@echo "... src/Source/MpdAudioSource.i"
	@echo "... src/Source/MpdAudioSource.s"
	@echo "... src/Source/PortAudioSource.o"
	@echo "... src/Source/PortAudioSource.i"
	@echo "... src/Source/PortAudioSource.s"
	@echo "... src/Source/PulseAudioSource.o"
	@echo "... src/Source/PulseAudioSource.i"
	@echo "... src/Source/PulseAudioSource.s"
	@echo "... src/Source/ShmemAudioSource.o"
	@echo "... src/Source/ShmemAudioSource.i"
	@echo "... src/Source/ShmemAudioSource.s"
	@echo "... src/Transformer/EllipseTransformer.o"
	@echo "... src/Transformer/EllipseTransformer.i"
	@echo "... src/Transformer/EllipseTransformer.s"
	@echo "... src/Transformer/GenericTransformer.o"
	@echo "... src/Transformer/GenericTransformer.i"
	@echo "... src/Transformer/GenericTransformer.s"
	@echo "... src/Transformer/LorenzTransformer.o"
	@echo "... src/Transformer/LorenzTransformer.i"
	@echo "... src/Transformer/LorenzTransformer.s"
	@echo "... src/Transformer/SpectrumCircleTransformer.o"
	@echo "... src/Transformer/SpectrumCircleTransformer.i"
	@echo "... src/Transformer/SpectrumCircleTransformer.s"
	@echo "... src/Transformer/SpectrumTransformer.o"
	@echo "... src/Transformer/SpectrumTransformer.i"
	@echo "... src/Transformer/SpectrumTransformer.s"
	@echo "... src/Utils/ConfigurationUtils.o"
	@echo "... src/Utils/ConfigurationUtils.i"
	@echo "... src/Utils/ConfigurationUtils.s"
	@echo "... src/Utils/Logger.o"
	@echo "... src/Utils/Logger.i"
	@echo "... src/Utils/Logger.s"
	@echo "... src/Utils/NcursesUtils.o"
	@echo "... src/Utils/NcursesUtils.i"
	@echo "... src/Utils/NcursesUtils.s"
	@echo "... src/Utils/Utils.o"
	@echo "... src/Utils/Utils.i"
	@echo "... src/Utils/Utils.s"
	@echo "... src/Visualizer.o"
	@echo "... src/Visualizer.i"
	@echo "... src/Visualizer.s"
	@echo "... src/Writer/NcursesWriter.o"
	@echo "... src/Writer/NcursesWriter.i"
	@echo "... src/Writer/NcursesWriter.s"
	@echo "... src/vis.o"
	@echo "... src/vis.i"
	@echo "... src/vis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

